[package]
name = "snippext"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/doctavious/snippext"
keywords = ["snippet"]
categories = ["documentation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#name = "snippext"
#path = "src/lib.rs"
#
#[[bin]]
#name = "snippext-cli"
#path = "src/main.rs"

[dependencies]
clap = "2.33.3"
# https://github.com/mehcode/config-rs/blob/master/examples/hierarchical-env/src/settings.rs
config = "0.11"
git2 = "0.13"
glob = "0.3.0"
handlebars = "4.1.3"
lazy_static = "1"
regex = { version = "1", default-features = false, features = ["std", "unicode-case"] }
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
thiserror = "1.0.29"

[dev-dependencies]
tempfile = "3.2.0"
