begin: "snippet::"
end: "end::"
extension: "md"
comment_prefixes:
- "// "
- "# "
- "<!-- "
templates:
- name: "default"
  template: "{{snippet}}"
  default: true
sources:
# extract from local files
- files:
  - "**"
output_dir: "./generated-snippets/"
