# snippext::start default_snippext_config
start: "snippet::start"
end: "snippet::end"
templates:
  default: "```{{lang}}\n{{snippet}}```{{#unless omit_source_link}}\n<a href='{source_link}' title='Snippet source file'>snippet source</a>{{/unless}}"
  raw: "{{snippet}}"
sources:
# extract from local files
- !Local
  files:
  - "**"

# extract from remote Git repo
#- !Git
#  repository: https://github.com/doctavious/snippext.git
#  branch: main
#  cone_patterns:
#    - ./src/*.rs
#  files:
#    - "**"

# extract from URL
#- !Url http://localhost/hi

output_dir: "./generated-snippets/"
output_extension: "md"
# targets
# link_format
omit_source_links: false
missing_snippets_behavior: Warn
retain_nested_snippet_comments: false
enable_autodetect_language: true
selected_lines_include_ellipses: false
# snippext::end
