start: "snippet::start"
end: "snippet::end"
templates:
  default: "```{{lang}}\n{{snippet}}\n```{{#unless omit_source_link}}\n<a href='{source_link}' title='Snippet source file'>snippet source</a>{{/unless}}"
  raw: "{{snippet}}"
sources:
# extract from local files
- files:
  - "**"
output_dir: "./generated-snippets/"
output_extension: "md"

