# snippext::start default_snippext_config
start: "snippet::start"
end: "snippet::end"
templates:
  default: |-
    ```{{lang}}
    {{snippet~}}
    ```
    {{#unless omit_source_link}}
    <a href='{{source_link}}' title='Snippet source file'>snippet source</a>
    {{/unless}}
  raw: "{{snippet}}"
sources:
# extract from local files
- !Local
  files:
  - "**"

# extract from remote Git repo
#- !Git
#  repository: https://github.com/doctavious/snippext.git
#  branch: main
#  cone_patterns:
#    - ./src/*.rs
#  files:
#    - "**"

# extract from URL
#- !Url http://localhost/hi

output_dir: "./generated-snippets/"
output_extension: "md"  # Extension for generated files written to the output directory
# targets: ./docs  # List of glob patters, separated by spaces, that contain the files to be spliced with the code snippets.
# link_format: GitHub  # Defines the format of snippet source links that appear under each snippet.
omit_source_links: false
missing_snippets_behavior: Warn
retain_nested_snippet_comments: false
enable_autodetect_language: true
selected_lines_include_ellipses: false
# snippext::end